pre-release-replacements = [
    { file = "docs/lib.md", search = """gen-changelog = "\\d+.\\d+.\\d+"""", replace = "{{crate_name}} = \"{{version}}\"", exactly = 1 },
    { file = "PRLOG.md", search = "## \\[Unreleased\\]", replace = "## [{{version}}] - {{date}}", exactly = 1 },
    { file = "PRLOG.md", search = "\\[Unreleased\\]:", replace = "[{{version}}]:", exactly = 1 },
    { file = "PRLOG.md", search = "\\.\\.\\.HEAD", replace = "...{{tag_name}}", exactly = 1 },
]
pre-release-commit-message = "chore: Release {{crate_name}} v{{version}}"
tag-message = "{{tag_name}}"
tag-name = "{{prefix}}v{{version}}"
sign-tag = true
sign-commit = true
consolidate-commits = false
allow-branch = ["main"]
pre-release-hook = ["./release-hook.sh"]
